"""empty message

Revision ID: d7721b7a399d
Revises: 56f3911e5550
Create Date: 2023-09-22 14:06:27.781935

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd7721b7a399d'
down_revision = '56f3911e5550'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user','subscription')


def downgrade():
    op.add_column('user','subscription', sa.VARCHAR(length=100))